name: dartus
description: A Dart client for Tomuss
version: 1.0.2

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  dotenv: ^3.0.0
  lints: ^1.0.0
  test: ^1.20.1
dependencies: 
  beautiful_soup_dart: ^0.2.0
  cookie_jar: ^3.0.1
  dartz: ^0.10.1
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
